$(function(){
	$("#list").datagrid({
		url:"/php/index.php/manage/news/initData",
		columns:[[
		          {field:'id',title:'ID',width:100},  
		          {field:'name',title:'Name',width:100}
		          ]]
	})
})